<a href="https://colab.research.google.com/github/jotaeleb/tif-ciencias-de-datos/blob/main/notebooks/proyecto_modelado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🛡️TIF Análisis de Detección de Intrusiones en Red

**Grupo 1**: Gonza Gabriela · Casasola Hernán · Biazutti Luciano · Lera Aníbal Iván · Alvarado Marcelo

**Módulo**: Ciencias de Datos y Optimización de Modelos

**Carrera**: Tecnicatura Universitaria en Ciencias de Datos e IA Aplicada — UPATECO

---

# 1. Librerías

In [58]:
import io
import requests

import numpy as np
import pandas as pd

from datetime import datetime

from pandas.api.types import is_string_dtype

from xgboost import XGBClassifier

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.pipeline import make_pipeline
from sklearn.metrics import make_scorer, f1_score, recall_score, accuracy_score, classification_report

from imblearn.over_sampling import SMOTE

from IPython.display import display, HTML

# 2. Funciones auxiliares

In [54]:
#Esta función carga un dataset desde el repo de Github
def cargarDataset(archivos):

  GITHUB_USER = 'jotaeleb'
  GITHUB_REPO = 'tif-ciencias-de-datos'
  GITHUB_BRANCH = 'main'
  DATASET_DIR = 'dataset'

  BASE_URL = (
    f'https://raw.githubusercontent.com/'
    f'{GITHUB_USER}/{GITHUB_REPO}/{GITHUB_BRANCH}/{DATASET_DIR}'
  )

  partes = []
  for archivo in archivos:
    url = f'{BASE_URL}/{archivo}'
    print(f"Cargando archivo {url}")
    partes.append(pd.read_parquet(io.BytesIO(requests.get(url).content)))


  completo = pd.concat(partes,ignore_index=True)
  completo['Label'] = completo['Label'].str.replace(r'[^\w\s-]', '-', regex=True)

  return completo

#Esta función devuelve las columnas numéricas del dataset
def colNumericas(dFrame):
  columnas = []
  for columna, tipoDato in dFrame.dtypes.items():
    if not is_string_dtype(tipoDato):
      columnas.append(columna)
  return columnas

#Esta función evalúa el modelo
def evaluarModelo(y_prueba, predicciones,clases=None):
  accuracy = accuracy_score(y_prueba, predicciones)
  f1Macro = f1_score(y_prueba, predicciones, average='macro')
  print(f"Accuracy: {accuracy:.3f} | F1 Macro: {f1Macro:.3f}")

  if (clases is not None):
    reporte = classification_report(y_prueba,predicciones,target_names=clases,output_dict=True)
  else:
    reporte = classification_report(y_prueba,predicciones,output_dict=True)


  dfReporte = pd.DataFrame(reporte).transpose()

  dfReporte = dfReporte.round(4)

  display(HTML(dfReporte.to_html()))

  #Esta función lista categorias codificadas
  def verCategorias():
    pass

##  Carga Dataset limpio con submuestreo
---

In [8]:
print("--> Carga Dataset <--")
df = cargarDataset(["dataset_limpio_submuestreo.parquet"])
print(df.shape)

--> Carga Dataset <--
Cargando archivo https://raw.githubusercontent.com/jotaeleb/tif-ciencias-de-datos/main/dataset/dataset_limpio_submuestreo.parquet
(168004, 66)

##  Categorías
---

In [9]:
df['Label'].value_counts()

Label
BENIGN         50000
PortScan       50000
DoS-DDoS       50000
Brute Force    13826
Web Attack      2159
Botnet          1956
Rare Attack       63
Name: count, dtype: int64

## Pre requisitos comunes para los modelos Baseline
---

In [23]:
#Obtener listado de las columnas numéricas del dataset
columnas = colNumericas(df)

#Asignar a X las columnas numéricas del dataset
X = df[columnas]

#Asignar a etiqueta (Y) la variable objetivo
etiqueta = df["Label"]

##  Modelo Baseline Dummy
---

In [55]:
X_treino, X_prueba, y_treino, y_prueba = train_test_split(X, etiqueta, test_size=0.2, random_state=42, stratify=etiqueta)

modeloBaselineDummy = DummyClassifier(strategy='stratified')

modeloBaselineDummy.fit(X_treino, y_treino)

predicciones = modeloBaselineDummy.predict(X_prueba)

evaluarModelo(y_prueba, predicciones)

Accuracy: 0.268 | F1 Macro: 0.140

## Modelo Baseline Regresión Logística
---

In [35]:
X_treino, X_prueba, y_treino, y_prueba = train_test_split(X, etiqueta, test_size=0.2, random_state=42, stratify=etiqueta)

modeloBaselineRegresionLogistica = make_pipeline(
  StandardScaler(),
  LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)
)

modeloBaselineRegresionLogistica.fit(X_treino, y_treino)

predicciones = modeloBaselineRegresionLogistica.predict(X_prueba)
evaluarModelo(y_prueba, predicciones)

Accuracy: 0.951 | F1 Macro: 0.762

## Modelo Baseline XGBoost
---

In [56]:
label_encoder = LabelEncoder()

y_XGBoost = label_encoder.fit_transform(etiqueta)

X_treino, X_prueba, y_treino, y_prueba = train_test_split(X, y_XGBoost, test_size=0.2, random_state=42, stratify=etiqueta)

modeloBaselineXGBoost = XGBClassifier(
        objective='multi:softprob',
        eval_metric='mlogloss',
        random_state=42,
        n_estimators=300,
        max_depth=6,
        learning_rate=0.1,
        subsample=0.8,
        colsample_bytree=0.8
    )

modeloBaselineXGBoost.fit(X_treino, y_treino)
predicciones = modeloBaselineXGBoost.predict(X_prueba)
evaluarModelo(y_prueba, predicciones,label_encoder.classes_)

Accuracy: 0.999 | F1 Macro: 0.965

## Modelo Baseline XGBoost + SMOTE
---

In [61]:
label_encoder = LabelEncoder()

y_XGBoost = label_encoder.fit_transform(etiqueta)

mapeoEtiquetas = dict(zip(label_encoder.classes_,range(len(label_encoder.classes_))))

print(mapeoEtiquetas)

X_treino, X_prueba, y_treino, y_prueba = train_test_split(X, y_XGBoost, test_size=0.2, random_state=42, stratify=etiqueta)

smote = SMOTE(
        sampling_strategy={
            mapeoEtiquetas['Brute Force']: 20000,
            mapeoEtiquetas['Web Attack']: 12000,
            mapeoEtiquetas['Botnet']: 12000,
            mapeoEtiquetas['Rare Attack']: 4000
        },
        k_neighbors=3,  # reducir k porque Rare Attack tiene solo 63
        random_state=42)

X_balanceado, y_balanceado = smote.fit_resample(X_treino, y_treino)

print("Clases balanceadas con SMOTE")
valores, frecuencias = np.unique(y_balanceado, return_counts=True)

for clase, freq in zip(valores, frecuencias):
  print(f"{label_encoder.inverse_transform([clase])[0]}: {freq}")

modeloBaselineXGBoost = XGBClassifier(
        objective='multi:softprob',
        eval_metric='mlogloss',
        random_state=42,
        n_estimators=300,
        max_depth=6,
        learning_rate=0.1,
        subsample=0.8,
        colsample_bytree=0.8
    )

modeloBaselineXGBoost.fit(X_balanceado, y_balanceado)
predicciones = modeloBaselineXGBoost.predict(X_prueba)
evaluarModelo(y_prueba, predicciones,label_encoder.classes_)

{'BENIGN': 0, 'Botnet': 1, 'Brute Force': 2, 'DoS-DDoS': 3, 'PortScan': 4, 'Rare Attack': 5, 'Web Attack': 6}
Clases balanceadas con SMOTE
BENIGN: 40000
Botnet: 12000
Brute Force: 20000
DoS-DDoS: 40000
PortScan: 40000
Rare Attack: 4000
Web Attack: 12000
Accuracy: 0.999 | F1 Macro: 0.945